# PANDAS

In [1]:
import pandas as pd

In [2]:
emp=pd.read_csv("employees.csv")
emp.head()

FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'

In [ ]:
df=pd.read_excel("employees.xlsx")
df.head(3)

FileNotFoundError: [Errno 2] No such file or directory: 'employees.xlsx'

# Filtering Rows
combine condition with & (and) / | (or).ConnectionAbortedError
    wrap each condtion in parentheses

In [4]:
student={
    'Name':['Rahul','Sneha','Arjun','Divya','Karan'],
    'Age' :[21,22,21,23,22],
    'Marks': [78,91,64,88,55],
    'city' : ['Delhi','Pune','Jaipur','Delsi','Pune']
}
df=pd.DataFrame(student)
df

    Name  Age  Marks    city
0  Rahul   21     78   Delhi
1  Sneha   22     91    Pune
2  Arjun   21     64  Jaipur
3  Divya   23     88   Delsi
4  Karan   22     55    Pune

Series- A Single Column

In [5]:
marks=pd.Series([78,91,64,88,55],name='Marks')
print(marks)
print('\nType:',type(marks))

0    78
1    91
2    64
3    88
4    55
Name: Marks, dtype: int64

Type: <class 'pandas.Series'>

In [8]:
tempe=pd.Series([30,32,29,35])
print(tempe.mean())

31.5

In [36]:
student=pd.DataFrame({
    'Name':['Rahul','Sneha','Arjun','Divya','Karan'],
    'Age' :[21,22,'null',23,'null'],
    'Marks': [78,91,64,88,55],
    'city' : ['Delhi','Pune','Jaipur','Delhi','Pune']
})
student.to_csv('student.csv',index=False)
stu=pd.read_csv('student.csv')
stu

    Name   Age  Marks    city
0  Rahul  21.0     78   Delhi
1  Sneha  22.0     91    Pune
2  Arjun   NaN     64  Jaipur
3  Divya  23.0     88   Delhi
4  Karan   NaN     55    Pune

In [37]:
print('shap(row,col):',stu.shape)
print('Describe:',stu.describe())

shap(row,col): (5, 4)
Describe:         Age      Marks
count   3.0   5.000000
mean   22.0  75.200000
std     1.0  15.449919
min    21.0  55.000000
25%    21.5  64.000000
50%    22.0  78.000000
75%    22.5  88.000000
max    23.0  91.000000

In [38]:
stu.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     3 non-null      float64
 2   Marks   5 non-null      int64
 3   city    5 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 341.0 bytes

In [39]:
stu.head(2)

    Name   Age  Marks   city
0  Rahul  21.0     78  Delhi
1  Sneha  22.0     91   Pune

In [40]:
stu.shape

(5, 4)

In [41]:
stu.tail(2)

    Name   Age  Marks   city
3  Divya  23.0     88  Delhi
4  Karan   NaN     55   Pune

In [42]:

citys=stu[stu['city']=='Pune']
print(citys)

    Name   Age  Marks  city
1  Sneha  22.0     91  Pune
4  Karan   NaN     55  Pune

In [43]:
dt=stu[(stu['city']=='Delhi') & (stu['Age']<22)]
print(dt)

    Name   Age  Marks   city
0  Rahul  21.0     78  Delhi

In [44]:
dt=stu[stu['Age']>22]
print(dt)

    Name   Age  Marks   city
3  Divya  23.0     88  Delhi

In [45]:
stu.sort_values('Age', ascending=True)

    Name   Age  Marks    city
0  Rahul  21.0     78   Delhi
1  Sneha  22.0     91    Pune
3  Divya  23.0     88   Delhi
2  Arjun   NaN     64  Jaipur
4  Karan   NaN     55    Pune

In [46]:
stu.isnull().sum()

Name     0
Age      2
Marks    0
city     0
dtype: int64

In [ ]:
stu.head(
    
)

    Name   Age  Marks    city
0  Rahul  21.0     78   Delhi
1  Sneha  22.0     91    Pune
2  Arjun   NaN     64  Jaipur
3  Divya  23.0     88   Delhi
4  Karan   NaN     55    Pune

In [53]:
stu['Age']=stu['Age'].fillna(stu['Age'].mean())
stu.head()

    Name   Age  Marks    city
0  Rahul  21.0     78   Delhi
1  Sneha  22.0     91    Pune
2  Arjun  22.0     64  Jaipur
3  Divya  23.0     88   Delhi
4  Karan  22.0     55    Pune

#### 1. Load a fresh copy of employees.csv. 
#### 2. Clean all missing values (Salary mean, Experience-0). 
#### 3. Add a Seniority column: 'Senior if Experience>= 5, else 'Junior 
#### 4. Show the average Salary for Seniors vs Juniors.

In [64]:
df = pd.read_csv("employees.csv")
df.head()

   EmployeeID   Name   Salary  Experience Department
0         101   Amit  50000.0         2.0         IT
1         102  Priya  65000.0         6.0         HR
2         103  Rahul      NaN         4.0    Finance
3         104   Neha  80000.0         8.0         IT
4         105  Vikas  55000.0         NaN      Sales

In [65]:
# Fill missing values
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["Experience"] = df["Experience"].fillna(0)

In [67]:
# Add Seniority column
seniority=[]
for x in df['Experience']:
    if x>=5:
        seniority.append('Senior')
    else:
        seniority.append('Junior')
df['seniority']=seniority

In [68]:
# Show updated dataset
print(df)

   EmployeeID    Name   Salary  Experience Department seniority
0         101    Amit  50000.0         2.0         IT    Junior
1         102   Priya  65000.0         6.0         HR    Senior
2         103   Rahul  68375.0         4.0    Finance    Junior
3         104    Neha  80000.0         8.0         IT    Senior
4         105   Vikas  55000.0         0.0      Sales    Junior
5         106  Anjali  72000.0         7.0  Marketing    Senior
6         107   Rohit  68375.0         3.0         IT    Junior
7         108   Sneha  90000.0        10.0    Finance    Senior
8         109   Karan  60000.0         0.0         HR    Junior
9         110   Pooja  75000.0         5.0      Sales    Senior

In [70]:
# Average salary by Seniority
print("\nAverage Salary by Seniority:")
print(df.groupby("seniority")["Salary"].mean())

Average Salary by Seniority:
seniority
Junior    60350.0
Senior    76400.0
Name: Salary, dtype: float64